spring:
  jpa:
    hibernate.ddl-auto: update
  datasource:
    #    url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:/innovation/test
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

application:
  jwt:
    tokenExpirationAfterDays: 1
    secret: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: "Bearer "

server:
  port: 8080